(function initConstants(app) {
  const CARD_TYPES = [
    {
      id: "text",
      label: "Text",
      defaultColorTheme: "blue",
      editableFields: ["content"],
      searchableFields: [{ key: "content", label: "text content" }],
      hasBody: true,
    },
    {
      id: "board",
      label: "Board",
      defaultColorTheme: "teal",
      editableFields: [],
      searchableFields: [],
      hasBody: true,
    },
    {
      id: "link",
      label: "Link",
      defaultColorTheme: "violet",
      editableFields: ["url"],
      searchableFields: [{ key: "url", label: "link" }],
      hasBody: false,
      widthOnlyResize: true,
    },
    {
      id: "local-link",
      label: "Link (Local)",
      defaultColorTheme: "teal",
      editableFields: ["localPath", "localLinkMode"],
      searchableFields: [{ key: "localPath", label: "local link" }],
      hasBody: false,
      widthOnlyResize: true,
    },
    {
      id: "image",
      label: "Image",
      defaultColorTheme: "sky",
      editableFields: ["imagePath"],
      searchableFields: [],
      hasBody: true,
    },
    {
      id: "secret",
      label: "Secret",
      defaultColorTheme: "orange",
      editableFields: ["secret"],
      searchableFields: [],
      hasBody: false,
      widthOnlyResize: true,
    },
  ];
  const CARD_TYPE_DEFS = Object.fromEntries(CARD_TYPES.map((type) => [type.id, type]));
  const COLOR_THEME_ACCENTS = {
    slate: "#64748b",
    zinc: "#52525b",
    red: "#dc2626",
    orange: "#c2410c",
    amber: "#b45309",
    yellow: "#a16207",
    lime: "#4d7c0f",
    green: "#15803d",
    teal: "#0f766e",
    cyan: "#0e7490",
    sky: "#0369a1",
    blue: "#2563eb",
    indigo: "#4f46e5",
    violet: "#7c3aed",
    fuchsia: "#c026d3",
    rose: "#e11d48",
  };

  app.constants = {
    GRID_SIZE: 10,
    CARD_LAYER_OFFSET: 50000,
    DASHBOARD_WIDTH_UNITS: 500,
    DASHBOARD_HEIGHT_UNITS: 200,
    BOARD_CONTENT_WIDTH_UNITS: 120,
    BOARD_CONTENT_HEIGHT_UNITS: 80,
    MIN_CARD_WIDTH_UNITS: 8,
    MIN_CARD_HEIGHT_UNITS: 6,
    DEFAULT_CARD_WIDTH_UNITS: 24,
    DEFAULT_CARD_HEIGHT_UNITS: 14,
    PLACEMENT_GAP_UNITS: 1,
    PLACEMENT_SEARCH_RADIUS_UNITS: 240,
    LOCAL_STORAGE_FALLBACK_QUOTA_BYTES: 4 * 1024 * 1024,
    MOBILE_BREAKPOINT_PX: 720,
    STORAGE_KEY: "utilpage.dashboard.v1",
    CARD_TYPES,
    CARD_TYPE_DEFS,
    VALID_CARD_TYPES: new Set(CARD_TYPES.map((type) => type.id)),
    COLOR_THEME_ACCENTS,
    VALID_COLOR_THEMES: new Set(Object.keys(COLOR_THEME_ACCENTS)),
    ZOOM_MAX: 2.0,
    ZOOM_MIN: 0.5,
    ZOOM_STEP: 0.1,
  };
})(window.UtilPage ??= {});
