(function initConstants(app) {
  const CARD_TYPES = [
    {
      id: "text",
      label: "Text",
      defaultColorTheme: "blue",
      editableFields: ["content"],
      searchableFields: [{ key: "content", label: "text content" }],
      hasBody: true,
    },
    {
      id: "board",
      label: "Board",
      defaultColorTheme: "teal",
      editableFields: [],
      searchableFields: [],
      hasBody: true,
    },
    {
      id: "link",
      label: "Link",
      defaultColorTheme: "violet",
      editableFields: ["url"],
      searchableFields: [{ key: "url", label: "link" }],
      hasBody: false,
      widthOnlyResize: true,
    },
    {
      id: "local-link",
      label: "Link (Local)",
      defaultColorTheme: "teal",
      editableFields: ["localPath", "localLinkMode"],
      searchableFields: [{ key: "localPath", label: "local link" }],
      hasBody: false,
      widthOnlyResize: true,
    },
    {
      id: "image",
      label: "Image",
      defaultColorTheme: "sky",
      editableFields: ["imagePath"],
      searchableFields: [],
      hasBody: true,
    },
    {
      id: "secret",
      label: "Secret",
      defaultColorTheme: "orange",
      editableFields: ["secret"],
      searchableFields: [],
      hasBody: false,
      widthOnlyResize: true,
    },
  ];
  const CARD_TYPE_DEFS = Object.fromEntries(CARD_TYPES.map((type) => [type.id, type]));

  app.constants = {
    GRID_SIZE: 10,
    CARD_LAYER_OFFSET: 50000,
    DASHBOARD_WIDTH_UNITS: 500,
    DASHBOARD_HEIGHT_UNITS: 200,
    BOARD_CONTENT_WIDTH_UNITS: 120,
    BOARD_CONTENT_HEIGHT_UNITS: 80,
    MIN_CARD_WIDTH_UNITS: 8,
    MIN_CARD_HEIGHT_UNITS: 6,
    DEFAULT_CARD_WIDTH_UNITS: 24,
    DEFAULT_CARD_HEIGHT_UNITS: 14,
    PLACEMENT_GAP_UNITS: 1,
    PLACEMENT_SEARCH_RADIUS_UNITS: 240,
    MOBILE_BREAKPOINT_PX: 720,
    STORAGE_KEY: "utilpage.dashboard.v1",
    CARD_TYPES,
    CARD_TYPE_DEFS,
    VALID_CARD_TYPES: new Set(CARD_TYPES.map((type) => type.id)),
    VALID_COLOR_THEMES: new Set([
      "slate",
      "zinc",
      "red",
      "orange",
      "amber",
      "yellow",
      "lime",
      "green",
      "teal",
      "cyan",
      "sky",
      "blue",
      "indigo",
      "violet",
      "fuchsia",
      "rose",
    ]),
    ZOOM_MAX: 2.0,
    ZOOM_MIN: 0.5,
    ZOOM_STEP: 0.1,
  };
})(window.UtilPage ??= {});
